// <auto-generated />
namespace TestTcc2.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class pathModelToMusic : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(pathModelToMusic));
        
        string IMigrationMetadata.Id
        {
            get { return "201411112008442_pathModelToMusic"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
