// <auto-generated />
namespace TestTcc2.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class UsuarioMusica_Add_GeneroID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UsuarioMusica_Add_GeneroID));
        
        string IMigrationMetadata.Id
        {
            get { return "201505111848044_UsuarioMusica_Add_GeneroID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
