// <auto-generated />
namespace TestTcc2.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class change_PriceType_From_Musica : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_PriceType_From_Musica));
        
        string IMigrationMetadata.Id
        {
            get { return "201505152106471_change_PriceType_From_Musica"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
